name: Codez

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  codez:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/codex')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/codex')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '/codex'))
    runs-on: ubuntu-latest
    steps:
      - name: Run Codez
        uses: yiweishen/codez@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
